### ISSUE TITLE
User Info layout invasion

### ISSUE THREAD

**Issue by Senemix29** [Fleker/SmartNetworking#18]
When i am at the user info screen, and i scroll the user info fields, they are invading the blue user picture container. Can i solve this, to align this layout to be according ux best pratices ?
btw,  this could be one issue to hacktoberfest ? =D 
![screenshot_1476470150](https://cloud.githubusercontent.com/assets/6547509/19399092/229e9054-9226-11e6-82ba-c6f33a519c6d.png)
]

**Comment by Fleker** [comment]
Yes, please solve this if you know how. I did some hacky layout setup for
this to work.

**Comment by Senemix29** [comment]
Ok, i have made a pull request to handle with this issue. 
By the way, can you add the Hacktoberfest label, please ? =D
